// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bljviwlqcrneooyxgwik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsanZpd2xxY3JuZW9veXhnd2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzEwNjMsImV4cCI6MjA1NzY0NzA2M30.Y3R0yj5tjyhHEH0as84nGqjkAXOnLl6ILPeBJmL0LJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);